### ISSUE TITLE
Wrong palette icon

### ISSUE THREAD

**Issue by JoeXinfa** [spyder-ide/qtawesome#111]
The palette icon shows up as a T-shirt, not the palette as expected.
```
import qtawesome as qta
from qtpy.QtWidgets import QPushButton
from qtpy.QtWidgets import QApplication

app = QApplication([])
fa5_icon = qta.icon('fa5s.palette')
fa5_button = QPushButton(fa5_icon, 'palette')
fa5_button.show()
app.exec_()
```

```
(base) C:\Users>conda list qta
# packages in environment at C:\Users\joe\AppData\Local\Continuum\anaconda3:
#
# Name                    Version                   Build  Channel
qtawesome                 0.5.5                    py37_0
```

**Comment by darkvertex** [comment]
Can you try qtawesome 0.5.6 please? It was released January 25th and we fixed some things.

**Comment by ccordoba12** [comment]
I don't know if version 0.5.6 is available in Anaconda yet.

**Comment by darkvertex** [comment]
Looks like 0.5.6 is in Anaconda as of 2 days ago if I'm reading this page correctly? :point_down:
https://anaconda.org/conda-forge/qtawesome/files

**Comment by darkvertex** [comment]
Ah, well then I stand corrected.

I don't know much about the Anaconda public package release process... What does it take for the release to make it there? Does a human have to trigger it? Or is it a delayed weekly build sort of thing?

**Comment by ccordoba12** [comment]
> Does a human have to trigger it?

That was the case when I was working there. I don't know about know, but I think it's still the same.

**Comment by darkvertex** [comment]
So how do we get that refreshed? How do we ping them? :thinking:

**Comment by ccordoba12** [comment]
@jjhelmus, sorry to bother you, but do you have time to help us to create new packages for QtAwesome **0.5.6**? Thanks!

**Comment by jjhelmus** [comment]
`qtawesome` 0.5.6 is now available in `defaults`.  Note that this is a `noarch: python` package.

**Comment by ccordoba12** [comment]
Thanks a lot @jjhelmus!

@JoeXinfa, please update by running

    conda update qtawesome

in a system terminal and report again.

**Comment by JoeXinfa** [comment]
After update to 0.5.6, it works now. Thank you all for the quick helps, very appreciated!
